### ISSUE TITLE
Email is not fetched when a user is logging in from Github

### ISSUE THREAD

**Issue by SathyaBhat** [miled/wordpress-social-login#62]
When a user logs in using Github as the provider,  WP Social Login doesn't seem to be fetching the email id, hence creating a new user

**Comment by hubdotcom** [comment]
Seems like this has been resolved in the core hybridauth GitHub.php
https://github.com/hybridauth/hybridauth/commit/e5e9eae394a94342e51b68bbac4c17cca38e9d81

@miled - could I pull over the patches and update our version?

**Comment by miled** [comment]
@hubdotcom Please, feel free to send pull requests with updates.

**Comment by hubdotcom** [comment]
@SathyaBhat I've created an update using the latest hybridauth version. Could you please test this in your installation and confirm it's pulling the email address?

https://github.com/hubdotcom/wordpress-social-login/blob/fix-github-email-address/hybridauth/Hybrid/Providers/GitHub.php

**Comment by SathyaBhat** [comment]
@hubdotcom thanks for the merge.. but it still doesn't seem to be working ;( still creates new user, email is not pulled.

**Comment by hubdotcom** [comment]
I think this might need to be updated to use private_email_address - you can have a go at debugging by dumping the entire $data response and analyzing the data
